yversion: '3'

services:
  api:
    build:
      context: ./MY_API
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/db_test

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_test
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d  # Montage du répertoire contenant le script SQLDATABASES = {
    