# Generated by Django 5.0.4 on 2024-05-24 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_price',
            new_name='price',
        ),
    ]
