# Generated by Django 5.0.4 on 2024-05-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_detail_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
    ]
