# services:
#   api:
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     command: python manage.py runserver 0.0.0.0:8000
#     depends_on:
#       - db
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "db"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     environment:
#       - DATABASE_URL=mysql://user:password@db:3306/db
#       - DATABASE_NAME=db_test
#       - DATABASE_USER=root
#       - DATABASE_PASSWORD=password
#       - DATABASE_HOST=db
#       - DATABASE_PORT=3306  # N'oubliez pas de changer également cette ligne si vous changez le port de MySQL

#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db_test'
#       MYSQL_USER: 'root'
#       MYSQL_PASSWORD: 'password'
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       - '330:3306'
#     expose:
#       - '3306'
#     volumes:
#       - my-db:/var/lib/mysql

# volumes:
#   my-db:  
# version: '3.9'

# services:
#   api:
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#     command: python manage.py runserver 0.0.0.0:8000
#     depends_on:
#       - db
#     environment:
#       DATABASE_NAME: db_test
#       DATABASE_USER: root
#       DATABASE_PASSWORD: password
#       DATABASE_HOST: db
#       DATABASE_PORT: 3306
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "db", "-uroot", "-ppassword"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db_test'
#       MYSQL_ROOT_PASSWORD: 'password'  # Utilisation correcte de MYSQL_ROOT_PASSWORD
#     ports:
#       - '3307:3306'
#     expose:
#       - '3306'
#     volumes:
#       - my-db:/var/lib/mysql

# volumes:
#   my-db:


# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_URL=mysql://root:password@db:3306/db_test

#   db:
#     image: mysql:latest
#     ports:
#       - "3306:3306"
   
#     environment:
#        DATABASE_NAME: db_test
#        DATABASE_USER: root
#        DATABASE_PASSWORD: password
#        DATABASE_HOST: db
#        DATABASE_PORT: 3306
#     volumes:
#       - ./db_scripts:/docker-entrypoint-initdb.d

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/db_test
    command: ["sh", "-c", "while ! nc -z db 3306; do sleep 1; done && python manage.py runserver 0.0.0.0:5000"]

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       DATABASE_NAME: db_test
       DATABASE_USER: root
       DATABASE_PASSWORD: password
       DATABASE_HOST: db
       DATABASE_PORT: 3306
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d