services:
  api:
    build:
      context: .
    ports:
      - "5000:5000"
    command: python manage.py runserver
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10 
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/db_test

  db:
  
      POSTGRES_DB: db_test
      volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d  # Montage du répertoire contenant le script SQLDATABASES = {
    