version: '3.8'
services:
  api:
    build: "./"
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:password@db:3309/db_test

  db:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
       MYSQL_DATABASE: db_test
       MYSQL_ROOT_PASSWORD: password
       MYSQL_USER: tutu
       MYSQL_PASSWORD: password
       DATABASE_PASSWORD: password
       DATABASE_USER: root
       DATABASE_NAME: db_test
    volumes:
       - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DATABASE_NAME=db_test
#       - DATABASE_USER=root
#       - DATABASE_PASSWORD=password
#       - DATABASE_HOST=db
#       - DATABASE_PORT=3306

