services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/db_test
    command: ["sh", "-c", "while ! nc -z db 3306; do sleep 1; done && python manage.py runserver 0.0.0.0:5000"]

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       DATABASE_NAME: db_test
       DATABASE_USER: root
       DATABASE_PASSWORD: password
       DATABASE_HOST: db
       DATABASE_PORT: 3306
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d