services:
  api:
    build:
      context: .
    ports:
      - "5000:5000"
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:  